<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetEnv" Version="3.1.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.2-beta1" />
      <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

</Project>
